spring:
  datasource:
    url: jdbc:h2:mem:usuario
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8090
campanha:
  url: http://localhost:8080